/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package bomberosg1.vistas;

import bomberosg1.accesoadatos.*;
import bomberosg1.entidades.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gonza
 */
public class AsignarBrigada extends javax.swing.JInternalFrame {

    DefaultTableModel modelo = new DefaultTableModel();
    BrigadaData brigadaData = null;
    SiniestroData siniestroData = null;
    CuartelData cuartelData = null;

    /**
     * Creates new form AsignarBrigada
     */
    public AsignarBrigada() {
        initComponents();
        brigadaData = new BrigadaData();
        siniestroData = new SiniestroData();
        cuartelData = new CuartelData();
        armarCabecera();
        cargarSiniestros();
        comboCuartel();
//        cargarBrigada();

        //Este actionListener, obtiene las brigadas asociadas al cuartel
        jcCuarteles.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Cuartel cuartelSeleccionado = (Cuartel) jcCuarteles.getSelectedItem();
                int idCuartel = cuartelSeleccionado.getIdCuartel();
                List<Brigada> brigadasDelCuartel = brigadaData.obtenerBrigadasPorCuartel(idCuartel);

                // Limpiamos el JComboBox jcBrigadas
                jcBrigadas.removeAllItems();

                // Añadimos las brigadas del cuartel seleccionado al JComboBox jcBrigadas
                for (Brigada brigada : brigadasDelCuartel) {
                    jcBrigadas.addItem(brigada);
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaSiniestro = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jlDistBrigada = new javax.swing.JLabel();
        jbAsignar = new javax.swing.JButton();
        jbSalir = new javax.swing.JButton();
        jcCuarteles = new javax.swing.JComboBox<>();
        jcBrigadas = new javax.swing.JComboBox<>();
        jbSeleccionar = new javax.swing.JButton();
        jlDistCuartel = new javax.swing.JLabel();
        BrigmasCerca = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);

        jLabel1.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel1.setText("Siniestros - Asignacion de Brigadas");

        jLabel2.setText("----------------------------------------------------------------------------------------------------------------------------------------------");

        TablaSiniestro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TablaSiniestro);

        jLabel3.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel3.setText("Asignar Brigadas:");

        jLabel4.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel4.setText("Cuarteles:");

        jLabel5.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel5.setText("Brigadas:");

        jlDistBrigada.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jlDistBrigada.setText("Distancia:");
        jlDistBrigada.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jbAsignar.setText("Asignar");
        jbAsignar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAsignarActionPerformed(evt);
            }
        });

        jbSalir.setText("Salir");
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });

        jcCuarteles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcCuartelesActionPerformed(evt);
            }
        });

        jbSeleccionar.setText("Seleccionar");
        jbSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSeleccionarActionPerformed(evt);
            }
        });

        jlDistCuartel.setText("Distancia:");

        BrigmasCerca.setText("Mas cercana:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbSeleccionar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BrigmasCerca)))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbAsignar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbSalir))
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jcBrigadas, 0, 230, Short.MAX_VALUE)
                            .addComponent(jcCuarteles, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlDistBrigada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlDistCuartel)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)))
                .addContainerGap(43, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(221, 221, 221))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jcCuarteles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jlDistCuartel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jcBrigadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlDistBrigada, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbSeleccionar)
                    .addComponent(jbAsignar)
                    .addComponent(jbSalir)
                    .addComponent(BrigmasCerca))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcCuartelesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcCuartelesActionPerformed
        // TODO add your handling code here:
    
//        Cuartel cuartelselec = (Cuartel) jcCuarteles.getSelectedItem();
//        int idCuartel = cuartelselec.getIdCuartel();
//        int sinSelec = TablaSiniestro.getSelectedRow();
//        if (sinSelec >= 0) {
//            String sintipo = (String) TablaSiniestro.getValueAt(sinSelec, 1);
//            jcBrigadas.removeAllItems();
//            for (Brigada brgda : brigadaData.verBrigadas()) {
//                if (brgda.getNumeroCuartel().getIdCuartel() == idCuartel && brgda.getEspecialidad().contains(sintipo) && brgda.isLibre()) {
//                    jcBrigadas.addItem(brgda);
//                }
//            }
//        }
    }//GEN-LAST:event_jcCuartelesActionPerformed

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
        dispose();
    }//GEN-LAST:event_jbSalirActionPerformed

    private void jbSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSeleccionarActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jbSeleccionarActionPerformed

    private void jbAsignarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAsignarActionPerformed
        // TODO add your handling code here:
        try{

        Brigada codBrigada = (Brigada) jcBrigadas.getSelectedItem();
        int sinSelec =TablaSiniestro.getSelectedRow();
        int idSiniestro= (Integer)TablaSiniestro.getValueAt(sinSelec, 0);
        Siniestro nuevo= new Siniestro(idSiniestro,codBrigada);
        siniestroData.asignarElSiniestro(nuevo);

        boolean libre=false;
        int idBrigada = codBrigada.getIdBrigada();

        siniestroData.actualizarBrigada(idBrigada,libre);  
       
        renovarTabla();
              
        }catch(NullPointerException npe){
            JOptionPane.showMessageDialog(null, "Por favor, selecciona el Cuartel y la brigada", "Error", JOptionPane.ERROR_MESSAGE);
        }catch(ArrayIndexOutOfBoundsException a){
            JOptionPane.showMessageDialog(null, "Seleccione un siniestro","Error",JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jbAsignarActionPerformed

    private void armarCabecera() {
        modelo.addColumn("Id");
        modelo.addColumn("Tipo");
        modelo.addColumn("Fecha");
        modelo.addColumn("LongX");
        modelo.addColumn("LatiY");
        modelo.addColumn("Detalles");
        TablaSiniestro.setModel(modelo);
    }

    private void cargarSiniestros() {
        for (Siniestro siniestro : siniestroData.obtenerSiniestros()) {
            modelo.addRow(new Object[]{
                siniestro.getIdSiniestro(),
                siniestro.getTipo(),
                siniestro.getFechaSiniestro(),
                siniestro.getLongitudX(),
                siniestro.getLatitudY(),
                siniestro.getDetalles()
            });
        }
    }

    private void comboCuartel() {
        for (Cuartel listCuartel : cuartelData.verCuartel()) {
            jcCuarteles.addItem(listCuartel);
        }
    }

//    private void cargarBrigada() {
//        for (Brigada b : brigadaData.verBrigadas()) {
//            jcBrigadas.addItem(b);
//        }
//    }
//agregado para prueba calculo distancia
    public double calcularDistancia(double x1, double y1, double x2, double y2) {
        return Math.sqrt(Math.pow(x2 - x1, 2) + Math.pow(y2 - y1, 2));
    }

    private void actualizarBrigadasDisponibles(int idCuartel, String tipoSiniestro) {
        jcBrigadas.removeAllItems();

        for (Brigada brigada : brigadaData.verBrigadas()) {
            int idCuartelBrigada = brigada.getNumeroCuartel().getIdCuartel();
            String especialidad = brigada.getEspecialidad();

            if (idCuartelBrigada == idCuartel && especialidad.contains(tipoSiniestro) && brigada.isLibre()) {
                jcBrigadas.addItem(brigada);
            }
        }
    }
    
    private void renovarTabla() {
        modelo.setRowCount(0);
        cargarSiniestros();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BrigmasCerca;
    private javax.swing.JTable TablaSiniestro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbAsignar;
    private javax.swing.JButton jbSalir;
    private javax.swing.JButton jbSeleccionar;
    private javax.swing.JComboBox<Brigada> jcBrigadas;
    private javax.swing.JComboBox<Cuartel> jcCuarteles;
    private javax.swing.JLabel jlDistBrigada;
    private javax.swing.JLabel jlDistCuartel;
    // End of variables declaration//GEN-END:variables
}
