/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package bomberosg1.vistas;

import bomberosg1.accesoadatos.*;
import bomberosg1.entidades.*;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gonza
 */
public class FormBombero extends javax.swing.JInternalFrame {

    private DefaultTableModel modelo = new DefaultTableModel();
    BrigadaData bd = null;
    BomberoData bomData = null;

    /**
     * Creates new form FormBombero
     */
    public FormBombero() {
        bd = new BrigadaData();
        bomData = new BomberoData();
        initComponents();
        armarCabecera();
        cargarBomberos();//debe tener un error
        cargarBrigada();
        disabledd();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.ButtonGroup buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jtDni = new javax.swing.JTextField();
        jtNombre = new javax.swing.JTextField();
        jtApellido = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jtCelular = new javax.swing.JTextField();
        jcGrupoSang = new javax.swing.JComboBox<>();
        jcBrigadaAsignar = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jtDisponibilidad = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaBombero = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jbSeleccionar = new javax.swing.JButton();
        jdFechaNac = new com.toedter.calendar.JDateChooser();
        jrEstado = new javax.swing.JRadioButton();
        jLabel13 = new javax.swing.JLabel();
        jbEliminarDef = new javax.swing.JButton();
        jbNuevo = new javax.swing.JButton();
        jbGuardar = new javax.swing.JButton();
        jbModificar = new javax.swing.JButton();
        jbDarBaja = new javax.swing.JButton();
        jbSalir = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel1.setText("FORMULARIO BOMBERO");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel2.setText("DNI:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabel3.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel3.setText("Nombre:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, -1, -1));

        jLabel4.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel4.setText("Apellido:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, -1, -1));

        jLabel5.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel5.setText("Fecha de Nacimiento");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 70, -1, -1));

        jLabel6.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel6.setText("Grupo Sanguineo:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, -1, -1));

        jLabel7.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel7.setText("Celular:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabel8.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel8.setText("Asignar a Brigada:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, -1, -1));
        jPanel1.add(jtDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 90, -1));
        jPanel1.add(jtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 110, -1));
        jPanel1.add(jtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, 140, -1));

        jLabel9.setText("-------------------------------------------------------------------------------------------------------------------------");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));
        jPanel1.add(jtCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 90, -1));

        jcGrupoSang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-" }));
        jPanel1.add(jcGrupoSang, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 110, -1));

        jcBrigadaAsignar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcBrigadaAsignarActionPerformed(evt);
            }
        });
        jPanel1.add(jcBrigadaAsignar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 190, -1));

        jLabel10.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel10.setText("Disponibilidad:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 140, -1, -1));

        jtDisponibilidad.setEditable(false);
        jtDisponibilidad.setEnabled(false);
        jPanel1.add(jtDisponibilidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 160, 40, -1));

        TablaBombero.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TablaBombero);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 640, 130));

        jLabel11.setText("Espacios Dispo");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 160, -1, -1));

        jLabel12.setText("---------------------------------------------------------------------------------------------------------------------------");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        jbSeleccionar.setText("Seleccionar");
        jbSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSeleccionarActionPerformed(evt);
            }
        });
        jPanel1.add(jbSeleccionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));
        jPanel1.add(jdFechaNac, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 90, 130, -1));

        jrEstado.setText("Activo");
        jPanel1.add(jrEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 90, -1, -1));

        jLabel13.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel13.setText("Estado:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 70, -1, -1));

        jbEliminarDef.setText("EliminarDef");
        jbEliminarDef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEliminarDefActionPerformed(evt);
            }
        });
        jPanel1.add(jbEliminarDef, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 210, -1, -1));

        jbNuevo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jbNuevo.setText("Nuevo");
        jbNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNuevoActionPerformed(evt);
            }
        });

        jbGuardar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jbGuardar.setText("Guardar");
        jbGuardar.setEnabled(false);
        jbGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGuardarActionPerformed(evt);
            }
        });

        jbModificar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jbModificar.setText("Modificar");
        jbModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbModificarActionPerformed(evt);
            }
        });

        jbDarBaja.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jbDarBaja.setText("Dar Baja");
        jbDarBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDarBajaActionPerformed(evt);
            }
        });

        jbSalir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jbSalir.setText("Salir");
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 688, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jbNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(jbGuardar)
                .addGap(65, 65, 65)
                .addComponent(jbModificar)
                .addGap(67, 67, 67)
                .addComponent(jbDarBaja)
                .addGap(44, 44, 44)
                .addComponent(jbSalir))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbNuevo)
                    .addComponent(jbGuardar)
                    .addComponent(jbModificar)
                    .addComponent(jbDarBaja)
                    .addComponent(jbSalir))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
        dispose();
    }//GEN-LAST:event_jbSalirActionPerformed

    private void jbNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNuevoActionPerformed
        // TODO add your handling code here:
        enabledd();
        jbModificar.setEnabled(false);
        jbDarBaja.setEnabled(false);
        jbGuardar.setEnabled(true);
        limpiar();
    }//GEN-LAST:event_jbNuevoActionPerformed

    private void jbGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGuardarActionPerformed

        if (jtDni.getText().isEmpty() || jtNombre.getText().isEmpty() || jtApellido.getText().isEmpty() || jtCelular.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Complete los campos, Todos son obligatorios");
        } else {
            int dni = Integer.parseInt(jtDni.getText());
            if (bomData.existeBomberoConDni(dni)) {
                JOptionPane.showMessageDialog(this, "El bombero existe");
            } else {
                try {
                    String nombre = jtNombre.getText();
                    String apellido = jtApellido.getText();
                    Date fnac = jdFechaNac.getDate();
                    LocalDate feDate = fnac.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
                    String celular = jtCelular.getText();
                    String grupoSan = (String) jcGrupoSang.getSelectedItem();
                    Brigada brig = (Brigada) jcBrigadaAsignar.getSelectedItem();
                    boolean activo = jrEstado.isSelected();
                    Bombero bombero = new Bombero(dni, nombre, apellido, feDate, celular, brig, grupoSan, activo);
                    bomData.altaBombero(bombero);
                    disabledd();

                    modelo.setRowCount(0);
                    cargarBomberos();
//                    limpiar();
                } catch (Exception e) {
                    e.printStackTrace();
                }

            }
        }
        ///////////////////////////////////////////////
//        try {
//            if (jtDni.getText().isEmpty() || jtNombre.getText().isEmpty() || jtApellido.getText().isEmpty() || jtCelular.getText().isEmpty()) {
//                JOptionPane.showMessageDialog(null, "Complete los campos, Todos son obligatorios");
//            } else {
//                int dni = Integer.parseInt(jtDni.getText());
//                String nombre = jtNombre.getText();
//                String apellido = jtApellido.getText();
//                Date fnac = jdFechaNac.getDate();
//                LocalDate feDate = fnac.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
//                String grupoSan = (String) jcGrupoSang.getSelectedItem();
//                String celular = jtCelular.getText();
//                Boolean activo = true;
//                
//                Brigada brig = (Brigada) jcBrigadaAsignar.getSelectedItem();
//
//                Bombero bo = new Bombero(dni, nombre, apellido, feDate, celular, brig, grupoSan, true);
//                bomData.altaBombero(bo);
//                cargarBomberos();
//                
//                jbModificar.setEnabled(true);
//                jbDarBaja.setEnabled(true);
//            }
//        } catch (Exception e) {
//        }

        //////////////////////////////////////////////////////////
//          if(jtDni.getText().isEmpty()|| jtNombre.getText().isEmpty()|| jtApellido.getText().isEmpty()||jtCelular.getText().isEmpty()){
//            JOptionPane.showMessageDialog(null, "Complete los campos, Todos son obligatorios");
//        }else{
//            try {
//                int dni = Integer.parseInt(jtDni.getText());
//                String nombre = jtNombre.getText();
//                String apellido = jtApellido.getText();
//                Date fnac = jdFechaNac.getDate();
//                LocalDate feDate = fnac.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
//                String grupoSan = (String)jcGrupoSang.getSelectedItem();
//                String celular = jtCelular.getText();
//                Boolean activo = true;
//                Brigada brig = (Brigada)jcBrigadaAsignar.getSelectedItem();
//                
//                Bombero bo = new Bombero(dni, nombre, apellido, feDate, celular, brig, grupoSan, true);
//                bomData.altaBombero(bo);
//                cargarBomberos();
//                limpiar();
//            } catch (Exception e) {
//            }
//        }
//        

    }//GEN-LAST:event_jbGuardarActionPerformed

    private void jbSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSeleccionarActionPerformed

        enabledd();
        if (TablaBombero.getSelectedRow() != -1) {
            int dni = Integer.parseInt(String.valueOf(TablaBombero.getValueAt(TablaBombero.getSelectedRow(), 0)));
            for (Bombero bombero : bomData.verBomberos()) {
                if (dni == bombero.getDni()) {
                    int dniseleccionad = bombero.getIdBombero();
                    jtDni.setText(String.valueOf(bombero.getDni()));
                    jtNombre.setText(String.valueOf(bombero.getNombre()));
                    jtApellido.setText(String.valueOf(bombero.getApellido()));
                    jdFechaNac.setDate(java.util.Date.from(bombero.getFechaNac().atStartOfDay(ZoneId.systemDefault()).toInstant()));
                    jtCelular.setText(String.valueOf(bombero.getCelular()));
                    jrEstado.setSelected(bombero.isActivo());
                    for (int i = 0; i < jcGrupoSang.getItemCount(); i++) {
                        if (bombero.getGrupoSanguineo().contains(jcGrupoSang.getItemAt(i))) {
                            jcGrupoSang.setSelectedIndex(i);
                            break;
                        }
                    }
                    String var2 = bombero.getCodBrigada().getNombreBrigada();
                    for (int i = 0; i < jcBrigadaAsignar.getItemCount(); i++) {
                        if (var2.contains(jcBrigadaAsignar.getItemAt(i).getNombreBrigada())) {
                            jcBrigadaAsignar.setSelectedIndex(i);
                            break;
                        }

                    }
                    jbGuardar.setEnabled(false);
                    jbModificar.setEnabled(true);
                    jbDarBaja.setEnabled(true);

                    break;
                }
            }

        }

//        int filaSeleccionada = TablaBombero.getSelectedRow();
//        if(filaSeleccionada == -1){
//            JOptionPane.showMessageDialog(null, "No se seleccionó ninguna fila");
//            return;
//        }
//        Object dni = TablaBombero.getValueAt(filaSeleccionada, 0);
//        Object nombre = TablaBombero.getValueAt(filaSeleccionada, 1);
//        Object apellido = TablaBombero.getValueAt(filaSeleccionada, 2);
////        Object fechaNac = TablaBombero.getValueAt(filaSeleccionada, 3);
//        Object brigada = TablaBombero.getValueAt(filaSeleccionada, 3);
////        Object especialidad = TablaBombero.getValueAt(filaSeleccionada, 4);
//        
//        jtDni.setText(dni != null ? dni.toString() : "");
//        jtNombre.setText(nombre != null ? nombre.toString() : "");
//        jtApellido.setText(apellido != null ? nombre.toString() : "");
////        jdFechaNac.setDate(fechaNac != null ? fechaNac.toString() : "");
////        jcGrupoSang.setSelectedItem(especialidad != null ? especialidad.toString() : "");
////////brigada a asignar no funciona
//        jcBrigadaAsignar.setSelectedItem(brigada != null ? brigada.toString() : "");
//        
    }//GEN-LAST:event_jbSeleccionarActionPerformed

    private void jbDarBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDarBajaActionPerformed
        if (TablaBombero.getSelectedRow() != -1) {
            JOptionPane.showMessageDialog(null, "Seleccione");
        }
        for (Bombero listaBombero : bomData.verBomberos()) {
            int cambio = Integer.parseInt(jtDni.getText());
            if (cambio == listaBombero.getDni()) {
                if (!listaBombero.isActivo()) {
                    JOptionPane.showMessageDialog(null, "El bombero seleccionado se encuentra Inactivo");
                } else {
                    bomData.bajaBombero(listaBombero.getIdBombero());
//                limpiar();
//                cargarBomberos();
                }
            }
        }
//        try {
//            String seleccionado = TablaBombero.getValueAt(TablaBombero.getSelectedRow(), 1).toString();
//            Bombero bomberoSelec = null;
//            for (Bombero listBombero : bomData.verBomberos()) {
//                if (seleccionado.contains(listBombero.getNombre())) {
//                    bomberoSelec = listBombero;
//                    break;
//                }
//            }
//
//            if (bomberoSelec != null) {
//                int confirmar = JOptionPane.showConfirmDialog(null, "¿Seguro desea eliminar el bombero?");
//                if (confirmar == JOptionPane.YES_OPTION) {
//                    bomData.eliminarBombero(bomberoSelec.getIdBombero());
//                    modelo.setRowCount(0);
//                    cargarBomberos();
//                }
//            }
//        } catch (Exception e) {
//        }
//        int filaSeleccionada = TablaBombero.getSelectedRow();
//        if(filaSeleccionada != -1){
//            int idBombero = (int)TablaBombero.getValueAt(filaSeleccionada, 0);
//            bomData.eliminarBombero(idBombero);
////            cargarBomberos();
//            limpiar();
//        }else{
//            JOptionPane.showMessageDialog(null, "Seleccione un Bombero de la Tabla");
//        }
    }//GEN-LAST:event_jbDarBajaActionPerformed

    private void jbModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbModificarActionPerformed
        // TODO add your handling code here:
        try {
            if (TablaBombero.getSelectedRow() != -1) {
                // Obtener el objeto Bombero seleccionado
                int dniSeleccionado = Integer.parseInt(String.valueOf(TablaBombero.getValueAt(TablaBombero.getSelectedRow(), 0)));
                Bombero bomberoSeleccionado = null;

                for (Bombero bombero : bomData.verBomberos()) {
                    if (dniSeleccionado == bombero.getDni()) {
                        bomberoSeleccionado = bombero;
                        break;
                    }
                }

                if (bomberoSeleccionado != null) {
                    // Obtener la información actualizada de los campos de texto
                    int dni = Integer.parseInt(jtDni.getText());
                    String nombre = jtNombre.getText();
                    String apellido = jtApellido.getText();
                    Date fechaNac = jdFechaNac.getDate();
                    LocalDate fechaNacimiento = fechaNac.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
                    String celular = jtCelular.getText();
                    String grupoSan = (String) jcGrupoSang.getSelectedItem();
                    Brigada brigada = (Brigada) jcBrigadaAsignar.getSelectedItem();
                    boolean activo = jrEstado.isSelected();

                    // Actualizar los atributos del bombero seleccionado
                    bomberoSeleccionado.setDni(dni);
                    bomberoSeleccionado.setNombre(nombre);
                    bomberoSeleccionado.setApellido(apellido);
                    bomberoSeleccionado.setFechaNac(fechaNacimiento);
                    bomberoSeleccionado.setCelular(celular);
                    bomberoSeleccionado.setGrupoSanguineo(grupoSan);
                    bomberoSeleccionado.setCodBrigada(brigada);
                    bomberoSeleccionado.setActivo(activo);

                    // Llamar al método modificarBombero de BomberoData
                    bomData.modificarBombero(bomberoSeleccionado);

                    // Actualizar la tabla
                    modelo.setRowCount(0);
                    cargarBomberos();

                    // Limpiar los campos después de modificar
                    limpiar();

                    // Deshabilitar botones de modificar y dar de baja
                    jbModificar.setEnabled(false);
                    jbDarBaja.setEnabled(false);
                    jbGuardar.setEnabled(true);
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jbModificarActionPerformed

    private void jcBrigadaAsignarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcBrigadaAsignarActionPerformed
        // TODO add your handling code here:
        Brigada brigadaSelec = (Brigada) jcBrigadaAsignar.getSelectedItem();

        if (brigadaSelec != null) {
            int idBrigada = brigadaSelec.getIdBrigada();
            int cantidadBomberos = bomData.cantBomberosEnBrigada(idBrigada);
            int cantidadFaltante = Math.max(0, 5 - cantidadBomberos); // para evitar los valores negativos

            jtDisponibilidad.setText(String.valueOf(cantidadFaltante));
        }
    }//GEN-LAST:event_jcBrigadaAsignarActionPerformed

    private void jbEliminarDefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEliminarDefActionPerformed
        // TODO add your handling code here:
        try {
            String seleccionado = TablaBombero.getValueAt(TablaBombero.getSelectedRow(), 1).toString();
            Bombero bomberoSelec = null;
            for (Bombero listBombero : bomData.verBomberos()) {
                if (seleccionado.contains(listBombero.getNombre())) {
                    bomberoSelec = listBombero;
                    break;
                }
            }

            if (bomberoSelec != null) {
                int confirmar = JOptionPane.showConfirmDialog(null, "¿Seguro desea eliminar el bombero?");
                if (confirmar == JOptionPane.YES_OPTION) {
                    bomData.eliminarBombero(bomberoSelec.getIdBombero());
                    modelo.setRowCount(0);
                    cargarBomberos();
                }
            }
        } catch (Exception e) {
        }
        int filaSeleccionada = TablaBombero.getSelectedRow();
        if(filaSeleccionada != -1){
            int idBombero = (int)TablaBombero.getValueAt(filaSeleccionada, 0);
            bomData.eliminarBombero(idBombero);
//            cargarBomberos();
            limpiar();
        }else{
            JOptionPane.showMessageDialog(null, "Seleccione un Bombero de la Tabla");
        }
    }//GEN-LAST:event_jbEliminarDefActionPerformed

    private void armarCabecera() {
        modelo.addColumn("Dni");
        modelo.addColumn("Nombre");
        modelo.addColumn("Apellido");
        modelo.addColumn("Brigada");
        TablaBombero.setModel(modelo);
    }

    private void cargarBomberos() {
        for (Bombero bom : bomData.verBomberos()) {
            modelo.addRow(new Object[]{
                bom.getDni(),
                bom.getNombre(),
                bom.getApellido(),
                bom.getCodBrigada()
            });
        }
    }

    private void cargarBrigada() {
        for (Brigada b : bd.verBrigadas()) {
            jcBrigadaAsignar.addItem(b);
        }
    }

    private void limpiar() {
        jtDni.setText("");
        jtNombre.setText("");
        jtApellido.setText("");
        jtCelular.setText("");
        jcGrupoSang.setSelectedItem("Seleccione");
    }
    
    private void disabledd(){
        jtDni.setEnabled(false);
        jtNombre.setEnabled(false);
        jtApellido.setEnabled(false);
        jtCelular.setEnabled(false);
        jrEstado.setEnabled(false);
        jdFechaNac.setEnabled(false);
        jcGrupoSang.setEnabled(false);
        jcBrigadaAsignar.setEnabled(false);
    }
    
    private void enabledd(){
        jtDni.setEnabled(true);
        jtNombre.setEnabled(true);
        jtApellido.setEnabled(true);
        jtCelular.setEnabled(true);
        jrEstado.setEnabled(true);
        jdFechaNac.setEnabled(true);
        jcGrupoSang.setEnabled(true);
        jcBrigadaAsignar.setEnabled(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaBombero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbDarBaja;
    private javax.swing.JButton jbEliminarDef;
    private javax.swing.JButton jbGuardar;
    private javax.swing.JButton jbModificar;
    private javax.swing.JButton jbNuevo;
    private javax.swing.JButton jbSalir;
    private javax.swing.JButton jbSeleccionar;
    private javax.swing.JComboBox<Brigada> jcBrigadaAsignar;
    private javax.swing.JComboBox<String> jcGrupoSang;
    private com.toedter.calendar.JDateChooser jdFechaNac;
    private javax.swing.JRadioButton jrEstado;
    private javax.swing.JTextField jtApellido;
    private javax.swing.JTextField jtCelular;
    private javax.swing.JTextField jtDisponibilidad;
    private javax.swing.JTextField jtDni;
    private javax.swing.JTextField jtNombre;
    // End of variables declaration//GEN-END:variables
}
