/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package bomberosg1.vistas;

import bomberosg1.accesoadatos.*;
import bomberosg1.entidades.Bombero;
import bomberosg1.entidades.Brigada;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gonza
 */
public class ListadoDeBomberos extends javax.swing.JInternalFrame {

    private DefaultTableModel modelo = new DefaultTableModel();
    BrigadaData briData = null;
    BomberoData bomData = null;

    /**
     * Creates new form ListadoDeBomberos
     */
    public ListadoDeBomberos() {
        initComponents();
        briData = new BrigadaData();
        bomData = new BomberoData();
        armarCabecera();
        cargaBrigadas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaListBomb = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jcBrigadas = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jMenuBar1 = new javax.swing.JMenuBar();

        setClosable(true);
        setForeground(new java.awt.Color(0, 102, 102));
        setIconifiable(true);
        setResizable(true);
        setAutoscrolls(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Lista de Bomberos: ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(422, 6, -1, -1));

        TablaListBomb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TablaListBomb);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, 430, 240));

        jLabel2.setText("--------------------------------------------------------------------------------------");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, 440, -1));

        jLabel3.setText("Seleccione una Brigada para ver la Lista:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jcBrigadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcBrigadasActionPerformed(evt);
            }
        });
        jPanel1.add(jcBrigadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 210, -1));

        jLabel4.setText("Marque para ver aquellos Inactivos:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        jToggleButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jToggleButton1.setText("Inactivos");
        jPanel1.add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, -1, -1));

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcBrigadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcBrigadasActionPerformed
        // TODO add your handling code here:
//        limpiarTabla();
//        Brigada brigada=(Brigada)jcBrigadas.getSelectedItem();        
//        
//        if (brigada != null) {
//            List<Bombero> listaBomberos = bomData.verBomberos();
//        for(Bombero aux: listaBomberos){
//            modelo.addRow(new  Object[]{aux.getDni(), aux.getNombre(), aux.getApellido(),
//            aux.getFechaNac(),aux.getGrupoSanguineo(),aux.isActivo()
//                    }); 
//        }
//        }
        limpiarTabla();
        Brigada brigadaSel = (Brigada) jcBrigadas.getSelectedItem();
        int brigadaID = brigadaSel.getIdBrigada();
        for (Bombero aux : bomData.verBomberos()) {
            if (aux.getCodBrigada().getIdBrigada() == brigadaID) {
                modelo.addRow(new Object[]{
                    aux.getDni(),
                    aux.getNombre(),
                    aux.getApellido(),
                    aux.getFechaNac(),
                    aux.getGrupoSanguineo(),
                    aux.isActivo()
                });
            }
        }
    }//GEN-LAST:event_jcBrigadasActionPerformed

private void armarCabecera() {
        modelo.addColumn("Dni");
        modelo.addColumn("Nombre");
        modelo.addColumn("Apellido");
        modelo.addColumn("FechaNac");
        modelo.addColumn("GrupSangui");
        modelo.addColumn("Activo");
        TablaListBomb.setModel(modelo);
    }

    private void cargaBrigadas() {
        for (Brigada listaBrigadas : briData.verBrigadas()) {
            jcBrigadas.addItem(listaBrigadas);
        }
    }

    private void limpiarTabla() {
        modelo.setRowCount(0);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaListBomb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JComboBox<Brigada> jcBrigadas;
    // End of variables declaration//GEN-END:variables
}
