/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package bomberosg1.vistas;

import bomberosg1.accesoadatos.*;
import bomberosg1.entidades.*;
import java.util.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gonza
 */
public class ListadoBomberos extends javax.swing.JInternalFrame {

    private DefaultTableModel modelo = new DefaultTableModel();
    private List<Bombero> listaBomberos;
    private List<Brigada> listaBrigadas;

    private BomberoData bomberoData;
    private BrigadaData brigadaData;

    /**
     * Creates new form ListadoBomberos1
     */
    public ListadoBomberos() {
        initComponents();
        brigadaData = new BrigadaData();
        bomberoData = new BomberoData();
        armarCabecera();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TablaListado = new javax.swing.JTable();
        jcBrigadas = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        BotonInactivos = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jbDarDeAlta = new javax.swing.JButton();
        jbSalir = new javax.swing.JButton();

        TablaListado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TablaListado);

        jLabel3.setText("Seleccione una Brigada para ver la Lista:");

        jLabel4.setText("Marque para ver aquellos Inactivos:");

        BotonInactivos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BotonInactivos.setText("Inactivos");
        BotonInactivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonInactivosActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Lista de Bomberos: ");

        jLabel2.setText("--------------------------------------------------------------------------------------");

        jbDarDeAlta.setText("Dar de Alta");

        jbSalir.setText("Salir");
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jcBrigadas, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(BotonInactivos)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jbDarDeAlta)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbSalir))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 10, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(13, 13, 13)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(14, 14, 14)
                        .addComponent(jcBrigadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(128, 128, 128)
                        .addComponent(jLabel4)
                        .addGap(14, 14, 14)
                        .addComponent(BotonInactivos))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbDarDeAlta)
                    .addComponent(jbSalir))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonInactivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonInactivosActionPerformed
        // TODO add your handling code here:
        borrarFilaTabla();
        bomberosInactivos();
    }//GEN-LAST:event_BotonInactivosActionPerformed

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
        dispose();
    }//GEN-LAST:event_jbSalirActionPerformed

    private void armarCabecera() {
        ArrayList<Object>filaCabeceraList=new ArrayList<>();        
        filaCabeceraList.add("id");       
      //  filaCabeceraList.add("DNI");
        filaCabeceraList.add("nombre");
        filaCabeceraList.add("apellido");
      //  filaCabeceraList.add("fechaNac");
      //  filaCabeceraList.add("grupoSanguineo");
      //  filaCabeceraList.add("celular");
        filaCabeceraList.add("codBrigada");
        filaCabeceraList.add("activo");
        for(Object it: filaCabeceraList){
            modelo.addColumn(it);
        }
          TablaListado.setModel(modelo);
    }

    private void borrarFilaTabla() {
        int indice = modelo.getRowCount() - 1;
        for (int i = indice; i > 0; i--) {
            modelo.removeRow(i);//borramos las filas de atras p adelante
        }
    }
    
    private void cargarBrigadas(){
        for (Brigada auxBrigada: listaBrigadas){
            jcBrigadas.addItem(auxBrigada);
        }
    }
    
    private void cruceBomberoConBrigadas(){
        borrarFilaTabla();
        Brigada brigada=(Brigada)jcBrigadas.getSelectedItem();        
        listaBomberos=bomberoData.verBomberos();        
        for(Bombero aux: listaBomberos){
            modelo.addRow(new  Object[]{aux.getIdBombero(), aux.getNombre(), aux.getApellido(),
            aux.getCodBrigada(), aux.isActivo()});
        }
    }
    
    private void bomberosInactivos(){
         listaBomberos=bomberoData.bomberosInactivos();
         for(Bombero aux: listaBomberos){
            modelo.addRow(new  Object[]{aux.getIdBombero(), aux.getNombre(), aux.getApellido(),
            aux.getCodBrigada(), aux.isActivo()});
         }}
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton BotonInactivos;
    private javax.swing.JTable TablaListado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbDarDeAlta;
    private javax.swing.JButton jbSalir;
    private javax.swing.JComboBox<Brigada> jcBrigadas;
    // End of variables declaration//GEN-END:variables
}
