/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package bomberosg1.vistas;

import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gonza
 */
public class ResolucionDeSiniestros extends javax.swing.JInternalFrame {

    /**
     * Creates new form ResolucionDeSiniestros
     */
    public ResolucionDeSiniestros() {
        initComponents();
          armarCabecera();
    }
private DefaultTableModel modelo = new DefaultTableModel();
    // </editor-fold>



      private void armarCabecera() {
        modelo.addColumn("Fecha Resolucion");
        modelo.addColumn("Puntuacion Asignada");  
        TablaSiniestro.setModel(modelo);
    }
    
     private void limpiarCampos() {
        jdFechaResolucion.setDate(null);
        jTextField_puntuacion.setText(" ");
    }
     
       private void enabled(){
        jdFechaResolucion.setEnabled(true);
        jTextField_puntuacion.setEnabled(true);      
    }

                                              
                                             

private void llenarTabla(LocalDate fechaResolucion, Integer puntuacion) {
    Object[] rowData = {fechaResolucion, puntuacion};
    modelo.addRow(rowData);
}    
    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Subtitulo = new javax.swing.JLabel();
        jbSalir = new javax.swing.JButton();
        jbGuardar = new javax.swing.JButton();
        Titulo = new javax.swing.JLabel();
        jLabel_fechaResolucion = new javax.swing.JLabel();
        jLabel_puntuacion = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaSiniestro = new javax.swing.JTable();
        jdFechaResolucion = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jcPuntuacion = new javax.swing.JComboBox<>();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Subtitulo.setText("Formulario de Resolucion del Siniestro Afectado");
        getContentPane().add(Subtitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 79, 279, -1));

        jbSalir.setText("Salir");
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jbSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 390, 57, -1));

        jbGuardar.setText("Guardar");
        jbGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(jbGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(418, 391, -1, -1));

        Titulo.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        Titulo.setText("Siniestro");
        getContentPane().add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 96, -1));

        jLabel_fechaResolucion.setText("Fecha de Resolucion:");
        getContentPane().add(jLabel_fechaResolucion, new org.netbeans.lib.awtextra.AbsoluteConstraints(418, 79, -1, -1));

        jLabel_puntuacion.setText("Escriba su puntuacion:");
        getContentPane().add(jLabel_puntuacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(418, 181, 132, 30));

        TablaSiniestro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TablaSiniestro);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 109, 349, 305));
        getContentPane().add(jdFechaResolucion, new org.netbeans.lib.awtextra.AbsoluteConstraints(418, 109, 220, -1));

        jLabel1.setText("--------------------------------------------------------------------------------------------------------------------------------");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 51, -1, -1));

        jcPuntuacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        getContentPane().add(jcPuntuacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 210, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
        dispose();
    }//GEN-LAST:event_jbSalirActionPerformed

    private void jbGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGuardarActionPerformed
        enabled();
        if (jdFechaResolucion.getDate() == null || jTextField_puntuacion.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Complete los campos, Todos son obligatorios");
        } else {
            try {
                Date fresolucion = jdFechaResolucion.getDate();
                LocalDate feDate = fresolucion.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
                Integer puntuacion = Integer.parseInt(jTextField_puntuacion.getText().trim());

                llenarTabla(feDate, puntuacion);
                limpiarCampos();
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "La puntuación debe ser un número válido");
            }
        }

    }//GEN-LAST:event_jbGuardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Subtitulo;
    private javax.swing.JTable TablaSiniestro;
    private javax.swing.JLabel Titulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_fechaResolucion;
    private javax.swing.JLabel jLabel_puntuacion;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbGuardar;
    private javax.swing.JButton jbSalir;
    private javax.swing.JComboBox<String> jcPuntuacion;
    private com.toedter.calendar.JDateChooser jdFechaResolucion;
    // End of variables declaration//GEN-END:variables
}
